name: embed-mermaid-file
on:
  push:
    paths:
      - 'Shell.mermaid'
      - 'README.md'
  pull_request: 
    paths:
      - 'Shell.mermaid'
      - 'README.md'
jobs:
  replace-diagram:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - run: sed -i '/^```mermaid/,/^```/{/^```/!d}' README.md
      - run: sed -i '/^```mermaid/ r Shell.mermaid' README.md
      - run: |
          git add README.md
          git commit -m "Embed Mermaid Diagram"
